
copy_file_formats = [
        ".pdf",
        ".mp4",
        ".3gp",
        ".avi",
        ".wmv",
        ".mpeg",
        ".mpg",
        ".mov",
        ".flv",
        ".swf",
        ".qsv",
        ".kux",
        ".mpg",
        ".rm",
        ".ram",
        ".bmp",
        ".jpg",
        ".jpeg",
        ".jpe",
        ".jxr",
        ".png",
        ".tif",
        ".tiff",
        ".avif",
        ".xbm",
        ".pjp",
        ".svgz",
        ".ico",
        ".svg",
        ".jfif",
        ".webp",
        ".pjpeg",
        ".gif",
        ".iff",
        ".ilbm",
        ".ppm",
        ".pcx",
        ".xcf",
        ".xpm",
        ".psd",
        ".mng",
        ".sai",
        ".psp",
        ".ufo",
        ".mp3",
        ".mp2",
        ".mp1",
        ".wav",
        ".aif",
        ".aiff",
        ".au",
        ".ra",
        ".rm",
        ".ram",
        ".mid",
        ".rmi"
    ]


wayconfig =  {
    "html1_build_dir": "./html1_build",
    "html2_edit_dir": "./html2_edit",
    "html3_way_dir": "./html3_way",
    "html4_router_dir": "./html4_router",
    "auto_restart": True,
    "way_announce": True,
    "welcome_context": True,
    "welcome_got": False,
    "welcome_path": "./welcome.txt",
    "home_index_html": "./html1_build/index.html",
    "way_announce_str": "<script>console.log('\\\A/ Hi, Way! - An easy and fast front-end generator framework.');</script>",
    "browser_exe_path": "C:/Users/Administrator/AppData/Local/Google/Chrome/Application/chrome.exe",
    "auto_restart_seed": 1,
    "auto_generate_seed": 1,
    "auto_scaner_seed": 1,
    "way_write_file_formats": ['.html'],
    "copy_file_formats": copy_file_formats,
    "models_dir":'./models/',
    "models":['normal', 'flask'],
    "model_select": 1,
    "new_project": False,
}

